start failed (vibe-kanban 1f10a33e)
[2026-01-20 06:31:18] [ERROR] [uvicorn.error] Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 550, in \_prepare\_and\_execute

    self.\_rows = deque(await prepared\_stmt.fetch(\*parameters))

                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/asyncpg/prepared\_stmt.py", line 177, in fetch

    data = await self.\_\_bind\_execute(args, 0, timeout)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/asyncpg/prepared\_stmt.py", line 268, in \_\_bind\_execute

    data, status, \_ = await self.\_\_do\_execute(

                      ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/asyncpg/prepared\_stmt.py", line 257, in \_\_do\_execute

    return await executor(protocol)

           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "asyncpg/protocol/protocol.pyx", line 205, in bind\_execute

asyncpg.exceptions.DatatypeMismatchError: column "proxy\_enabled" is of type boolean but default expression is of type integer

HINT:  You will need to rewrite or cast the expression.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in \_exec\_single\_context

    self.dialect.do\_execute(

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 952, in do\_execute

    cursor.execute(statement, parameters)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 585, in execute

    self.\_adapt\_connection.await\_(

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/\_concurrency\_py3k.py", line 132, in await\_only

    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/\_concurrency\_py3k.py", line 196, in greenlet\_spawn

    value = await result

            ^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 563, in \_prepare\_and\_execute

    self.\_handle\_exception(error)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 513, in \_handle\_exception

    self.\_adapt\_connection.\_handle\_exception(error)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 797, in \_handle\_exception

    raise translated\_error from error

sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt\_asyncpg\_dbapi.ProgrammingError: <class 'asyncpg.exceptions.DatatypeMismatchError'>: column "proxy\_enabled" is of type boolean but default expression is of type integer

HINT:  You will need to rewrite or cast the expression.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 694, in lifespan

    async with self.lifespan\_context(app) as maybe\_state:

               ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 210, in \_\_aenter\_\_

    return await anext(self.gen)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 153, in merged\_lifespan

    async with original\_context(app) as maybe\_original\_state:

               ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 210, in \_\_aenter\_\_

    return await anext(self.gen)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 153, in merged\_lifespan

    async with original\_context(app) as maybe\_original\_state:

               ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 210, in \_\_aenter\_\_

    return await anext(self.gen)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 153, in merged\_lifespan

    async with original\_context(app) as maybe\_original\_state:

               ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/contextlib.py", line 210, in \_\_aenter\_\_

    return await anext(self.gen)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/app/backend/app/main.py", line 40, in lifespan

    await init\_db()

  File "/app/backend/app/db/session.py", line 77, in init\_db

    await conn.run\_sync(\_run\_migrations)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 888, in run\_sync

    return await greenlet\_spawn(

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/\_concurrency\_py3k.py", line 201, in greenlet\_spawn

    result = context.throw(\*sys.exc\_info())

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/backend/app/db/session.py", line 125, in \_run\_migrations

    ensure\_columns(

  File "/app/backend/app/db/session.py", line 97, in ensure\_columns

    sync\_conn.execute(text(f"ALTER TABLE {table} ADD COLUMN {ddl}"))

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1419, in execute

    return meth(

           ^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 527, in \_execute\_on\_connection

    return connection.\_execute\_clauseelement(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1641, in \_execute\_clauseelement

    ret = self.\_execute\_context(

          ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in \_execute\_context

    return self.\_exec\_single\_context(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in \_exec\_single\_context

    self.\_handle\_dbapi\_exception(

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2363, in \_handle\_dbapi\_exception

    raise sqlalchemy\_exception.with\_traceback(exc\_info[2]) from e

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in \_exec\_single\_context

    self.dialect.do\_execute(

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 952, in do\_execute

    cursor.execute(statement, parameters)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 585, in execute

    self.\_adapt\_connection.await\_(

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/\_concurrency\_py3k.py", line 132, in await\_only

    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/\_concurrency\_py3k.py", line 196, in greenlet\_spawn

    value = await result

            ^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 563, in \_prepare\_and\_execute

    self.\_handle\_exception(error)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 513, in \_handle\_exception

    self.\_adapt\_connection.\_handle\_exception(error)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 797, in \_handle\_exception

    raise translated\_error from error

sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.DatatypeMismatchError'>: column "proxy\_enabled" is of type boolean but default expression is of type integer

HINT:  You will need to rewrite or cast the expression.

[SQL: ALTER TABLE service\_providers ADD COLUMN proxy\_enabled BOOLEAN DEFAULT 0]

(Background on this error at: https://sqlalche.me/e/20/f405)

[2026-01-20 06:31:18] [ERROR] [uvicorn.error] Application startup failed. Exiting.